spring:
   profiles:
      activate: dev

---
# common: spring boot configuration
spring:

   # devtools - live reload
   livereload: 
      enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   # multipart
   multipart: 
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

   # aop(@EnableAspectJAutoProxy)
   aop:
      auto: true
      proxy-target-class: true

---

# dev profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: dev
   
   # datasource
   datasource: 
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.0.197:3307/jblog?characterEncoding=UTF-8&serverTimezone=UTC
      username: jblog
      password: jblog
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

---

# production profile: spring boot configuration
spring:
   config:
      activate:
         on-profile: production

   # datasource
   datasource: 
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://222.14.5.6:3307/jblog?characterEncoding=UTF-8&serverTimezone=UTC
      username: jblog
      password: jblogsadfa
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

---

# server
server:
   port: 8080
   servlet:
      context-path: /jblog06
      encoding:
         charset: utf-8
         enabled: true
         force: false
         force-request: false
         force-response: false

---

#mybatis
mybatis: 
   config-location: classpath:mybatis/configuration.xml

---

# logging
logging: 
   config: classpath:logback.xml
